# Generated by Django 5.2.6 on 2025-09-17 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('credit_card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('is_chargemap_pro_user', models.BooleanField(default=False)),
                ('invoices_count', models.IntegerField(default=0)),
                ('paid_invoices_count', models.IntegerField(default=0)),
                ('current_debt_amount', models.FloatField(default=0.0)),
                ('feedback_count', models.IntegerField(default=0)),
                ('payment_mean', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_time_avg', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fraud', models.BooleanField()),
                ('probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fraud_app.user')),
            ],
        ),
    ]
