# Generated by Django 5.2.6 on 2025-09-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_card_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
